package com.thatsit.android.parseutil;

public enum ParseOperationDecider {
	CREATE_ENTRY,
	FRIEND_REQUEST_SENT,
	FRIEND_REQUEST_RECEIVED,
	FRIEND_REQUEST_ACCEPTED,
	FRIEND_REQUEST_DECLINED,
	FRIEND_REQUEST_ACCEPTED_RESPONSE,
	FRIEND_REQUEST_DECLINED_RESPPONSE,
	DELETE_ENTRY
}
